# 是否启用信使
enable: true
# 您的信使频道, 无论channel的值如何，
# 只要保证不同转发客户端channel的值相同即可
channel: 943415354
id-base: 0
# 中间转发服务器,消息的桥梁.
# 默认为我个人提供的[NATS](https://github.com/nats-io/nats-server)服务器
nats:
  address: nats://itsusinn.site:4222
# 加密设置
cipher:
  # 是否启用加密
  enable: true
  # 加密用使用的密钥 需保证各端相同
  key: 8UeBN1h342OjD0yJ
  # 是否拒绝未经加密的消息
  refuse-plain: true
